# Generated by Django 4.1.9 on 2023-06-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('review_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
