# Generated by Django 4.1.9 on 2023-06-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_author_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='restapi.author'),
        ),
    ]
