# Generated by Django 4.1.9 on 2023-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_book_authors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-price', 'title'], name='price-title-index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='price-index'),
        ),
    ]
